before:
  hooks:
    - go mod tidy
builds:
  -
    id: headless
    binary: netclient
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_mips_hardfloat
      - linux_mips_softfloat
      - linux_mipsle_softfloat
      - linux_mipsle_hardfloat
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: arm
        goarm: "5"
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabi-gcc
      - goos: linux
        goarch: arm
        goarm: "6"
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabihf-gcc
      - goos: linux
        goarch: arm
        goarm: "7"
        env:
          - CGO_ENABLED=1
          - CC=arm-linux-gnueabihf-gcc
      - goos: linux
        goarch: mips
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mips-linux-gnu-gcc
      - goos: linux
        goarch: mips
        gomips: softfloat
        env:
          - CGO_ENABLED=0
      - goos: linux
        goarch: mipsle
        gomips: hardfloat
        env:
          - CGO_ENABLED=1
          - CC=mipsel-linux-gnu-gcc
      - goos: linux
        goarch: mipsle
        gomips: softfloat
        env:
          - CGO_ENABLED=0
      - goos: darwin
        env:
          - CGO_ENABLED=0
      - goos: windows
        env:
          - CGO_ENABLED=0

archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'
release:
  prerelease: false
